import { StyleSheet } from "react-native";

import type { AppColors } from "@presentation/theme/tokens";

// createAppStylesImpl keeps the exact StyleSheet key contract inferred in one place.
function createAppStylesImpl(colors: AppColors) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.backgroundPrimary },
    flex: { flex: 1 },
    authKeyboardView: { flex: 1, justifyContent: "center" },
    authContent: {
      width: "100%",
      maxWidth: 520,
      alignSelf: "center",
      gap: 24,
      padding: 20,
    },
    authHeader: { gap: 8 },
    authTitle: {
      color: colors.labelPrimary,
      fontSize: 34,
      fontWeight: "800",
      letterSpacing: -0.8,
    },
    authSubtitle: {
      color: colors.labelSecondary,
      fontSize: 15,
      lineHeight: 24,
    },
    authCard: {
      gap: 18,
      borderRadius: 24,
      padding: 18,
      backgroundColor: colors.backgroundSecondary,
    },
    authModeRow: {
      flexDirection: "row",
      gap: 6,
      padding: 3,
      borderRadius: 14,
      backgroundColor: colors.backgroundTertiary,
    },
    authModeButton: {
      flex: 1,
      minHeight: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 11,
    },
    authModeButtonActive: { backgroundColor: colors.systemBlue },
    authModeButtonText: {
      color: colors.labelSecondary,
      fontSize: 13,
      fontWeight: "800",
    },
    authModeButtonTextActive: { color: "#ffffff" },
    authMessage: {
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    authErrorMessage: { backgroundColor: `${colors.systemRed}1f` },
    authSuccessMessage: { backgroundColor: `${colors.systemGreen}1f` },
    authMessageText: {
      color: colors.labelPrimary,
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 19,
    },
    syncErrorBox: {
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: `${colors.systemRed}1f`,
    },
    syncErrorText: {
      color: colors.labelPrimary,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    screenContent: { gap: 18, padding: 20, paddingBottom: 118 },
    readerContent: { gap: 18, padding: 20, paddingBottom: 146 },
    modalScreen: { flex: 1, backgroundColor: colors.backgroundPrimary },
    modalContent: { gap: 16, padding: 20, paddingTop: 16, paddingBottom: 36 },
    modalHeader: {
      minHeight: 58,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 16,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
      backgroundColor: colors.backgroundPrimary,
    },
    modalTextButton: {
      minWidth: 72,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    modalTitle: {
      flex: 1,
      color: colors.labelPrimary,
      fontSize: 17,
      fontWeight: "800",
      textAlign: "center",
    },
    modalCancel: { color: colors.systemBlue, fontSize: 15, fontWeight: "600" },
    modalSave: { color: colors.systemBlue, fontSize: 15, fontWeight: "800" },
    homeHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 8,
    },
    readerHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      gap: 12,
      marginTop: 8,
    },
    readerBadge: {
      overflow: "hidden",
      borderRadius: 9,
      backgroundColor: `${colors.systemPurple}22`,
      color: colors.systemPurple,
      fontSize: 11,
      fontWeight: "900",
      paddingHorizontal: 9,
      paddingVertical: 5,
    },
    seriesDetailsHeader: {
      gap: 9,
      paddingVertical: 4,
    },
    largeTitle: {
      color: colors.labelPrimary,
      fontSize: 28,
      fontWeight: "700",
      letterSpacing: -0.6,
    },
    avatar: {
      width: 42,
      height: 42,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 21,
      backgroundColor: colors.systemBlue,
    },
    avatarText: { color: "#ffffff", fontSize: 13, fontWeight: "700" },
    appCategory: {
      color: colors.systemBlue,
      fontSize: 11,
      fontWeight: "800",
      letterSpacing: 0.7,
      marginBottom: 3,
    },
    roundActionButton: {
      width: 42,
      height: 42,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 21,
      backgroundColor: colors.systemBlue,
    },
    roundActionText: {
      color: "#ffffff",
      fontSize: 28,
      fontWeight: "600",
      lineHeight: 30,
    },
    secondaryText: {
      color: colors.labelSecondary,
      fontSize: 13,
      lineHeight: 19,
    },
    goalCard: {
      borderRadius: 22,
      backgroundColor: colors.backgroundSecondary,
      padding: 18,
    },
    continueBanner: {
      gap: 10,
      overflow: "hidden",
      borderRadius: 22,
      padding: 18,
      backgroundColor: colors.systemBlue,
    },
    seriesPrepareBanner: {
      backgroundColor: colors.systemPurple,
    },
    continueTag: {
      alignSelf: "flex-start",
      overflow: "hidden",
      borderRadius: 7,
      backgroundColor: "#ffffff30",
      color: "#ffffff",
      fontSize: 10,
      fontWeight: "900",
      letterSpacing: 0.8,
      paddingHorizontal: 8,
      paddingVertical: 4,
    },
    continueTitle: {
      color: "#ffffff",
      fontSize: 21,
      fontWeight: "900",
      letterSpacing: -0.3,
    },
    continueText: {
      color: "#ffffffe6",
      fontSize: 13,
      lineHeight: 19,
    },
    bannerButton: {
      alignSelf: "flex-start",
      minHeight: 38,
      justifyContent: "center",
      borderRadius: 12,
      paddingHorizontal: 14,
      backgroundColor: "#ffffff",
    },
    bannerButtonText: {
      color: "#000000",
      fontSize: 13,
      fontWeight: "800",
    },
    sectionLabel: {
      color: colors.labelSecondary,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.7,
      marginTop: 6,
    },
    actionList: {
      overflow: "hidden",
      borderRadius: 20,
      backgroundColor: colors.backgroundSecondary,
    },
    seriesList: {
      overflow: "hidden",
      borderRadius: 20,
      backgroundColor: colors.backgroundSecondary,
    },
    emptySeriesPanel: {
      gap: 8,
      minHeight: 104,
      justifyContent: "center",
      borderRadius: 20,
      padding: 18,
      backgroundColor: colors.backgroundSecondary,
    },
    seriesRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 104,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
    },
    rowActionStack: {
      alignItems: "flex-end",
      justifyContent: "center",
      gap: 8,
    },
    storyWordRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 76,
      paddingVertical: 10,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.separator,
    },
    seriesMeta: {
      overflow: "hidden",
      borderRadius: 8,
      backgroundColor: `${colors.systemBlue}22`,
      color: colors.systemBlue,
      fontSize: 11,
      fontWeight: "900",
      paddingHorizontal: 7,
      paddingVertical: 3,
    },
    seriesPremise: {
      color: colors.labelSecondary,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 7,
    },
    smallPrimaryButton: {
      minHeight: 36,
      justifyContent: "center",
      borderRadius: 12,
      paddingHorizontal: 12,
      backgroundColor: colors.systemBlue,
    },
    smallPrimaryButtonText: {
      color: "#ffffff",
      fontSize: 13,
      fontWeight: "800",
    },
    secondarySmallButton: {
      minHeight: 36,
      justifyContent: "center",
      borderRadius: 12,
      paddingHorizontal: 12,
      backgroundColor: colors.backgroundTertiary,
    },
    secondarySmallButtonText: {
      color: colors.labelPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    destructiveIconButton: {
      minHeight: 34,
      justifyContent: "center",
      borderRadius: 12,
      paddingHorizontal: 11,
      backgroundColor: `${colors.systemRed}1f`,
    },
    destructiveIconText: {
      color: colors.systemRed,
      fontSize: 12,
      fontWeight: "800",
    },
    actionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 76,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
    },
    actionIcon: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 12,
    },
    blueIcon: { backgroundColor: colors.systemBlue },
    purpleIcon: { backgroundColor: colors.systemPurple },
    orangeIcon: { backgroundColor: colors.systemOrange },
    actionIconText: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
    actionTitle: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "700",
      marginBottom: 3,
    },
    rowChevron: { color: colors.labelTertiary, fontSize: 28 },
    pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
    settingsCard: {
      gap: 14,
      padding: 16,
      borderRadius: 20,
      backgroundColor: colors.backgroundSecondary,
    },
    settingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    settingValue: {
      overflow: "hidden",
      borderRadius: 99,
      backgroundColor: `${colors.systemBlue}1f`,
      color: colors.systemBlue,
      fontSize: 12,
      fontWeight: "800",
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    cefrSegmentedControl: { height: 38 },
    settingMeter: { gap: 10 },
    stepperRow: { flexDirection: "row", gap: 10 },
    stepperButton: {
      flex: 1,
      minHeight: 38,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 12,
      backgroundColor: colors.backgroundTertiary,
    },
    stepperButtonText: {
      color: colors.labelPrimary,
      fontSize: 19,
      fontWeight: "800",
    },
    meterTrack: {
      height: 6,
      overflow: "hidden",
      borderRadius: 3,
      backgroundColor: colors.backgroundTertiary,
    },
    meterFill: {
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.systemBlue,
    },
    choiceRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 8,
    },
    goalChoice: {
      minWidth: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: colors.backgroundTertiary,
    },
    activeGoalChoice: { backgroundColor: colors.systemBlue },
    goalChoiceText: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "800",
    },
    activeGoalChoiceText: { color: "#ffffff" },
    formGroup: { gap: 8 },
    formInput: {
      minHeight: 48,
      borderRadius: 14,
      paddingHorizontal: 14,
      backgroundColor: colors.backgroundSecondary,
      color: colors.labelPrimary,
      fontSize: 15,
    },
    formTextArea: {
      minHeight: 108,
      paddingTop: 13,
      lineHeight: 21,
    },
    formErrorText: {
      color: colors.systemRed,
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 17,
      paddingHorizontal: 4,
    },
    formHelperText: {
      color: colors.labelSecondary,
      fontSize: 12,
      lineHeight: 17,
      paddingHorizontal: 4,
    },
    practiceCard: {
      gap: 12,
      padding: 18,
      borderRadius: 24,
      backgroundColor: colors.backgroundSecondary,
    },
    practiceWord: {
      color: colors.labelPrimary,
      fontSize: 34,
      fontWeight: "800",
      letterSpacing: -0.8,
    },
    practiceActions: { flexDirection: "row", gap: 10 },
    primaryButton: {
      minHeight: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 16,
      paddingHorizontal: 16,
      backgroundColor: colors.systemBlue,
    },
    primaryButtonText: {
      color: "#ffffff",
      fontSize: 15,
      fontWeight: "800",
    },
    secondaryButton: {
      flex: 1,
      minHeight: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 16,
      paddingHorizontal: 16,
      backgroundColor: colors.backgroundTertiary,
    },
    secondaryButtonText: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "800",
    },
    disabledControl: { opacity: 0.55 },
    genreRow: {
      minHeight: 54,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderRadius: 14,
      paddingHorizontal: 14,
      backgroundColor: colors.backgroundTertiary,
    },
    activeGenreRow: { backgroundColor: `${colors.systemBlue}1f` },
    offlineNotice: {
      gap: 6,
      marginTop: 14,
      padding: 14,
      borderRadius: 16,
      backgroundColor: `${colors.systemOrange}1f`,
    },
    readerRecap: {
      gap: 8,
      padding: 16,
      borderRadius: 18,
      backgroundColor: colors.backgroundSecondary,
    },
    readerStory: {
      gap: 10,
      paddingVertical: 4,
    },
    readerSentence: {
      borderRadius: 16,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    readerSentenceActive: {
      backgroundColor: `${colors.systemBlue}1f`,
      opacity: 1,
    },
    readerSentenceDimmed: {
      backgroundColor: "transparent",
      opacity: 0.48,
    },
    readerSentenceRest: {
      backgroundColor: "transparent",
      opacity: 1,
    },
    readerEpisodeBlock: {
      gap: 10,
      paddingBottom: 18,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
    },
    readerEpisodeHeading: {
      gap: 4,
      paddingHorizontal: 4,
    },
    readerSentenceText: {
      color: colors.labelPrimary,
      fontSize: 19,
      fontWeight: "500",
      lineHeight: 31,
    },
    readerDialogueFrame: {
      gap: 8,
    },
    readerDialogueBubble: {
      alignSelf: "flex-start",
      maxWidth: "94%",
      gap: 5,
      borderLeftWidth: 3,
      borderLeftColor: colors.systemBlue,
      borderRadius: 16,
      paddingHorizontal: 13,
      paddingVertical: 11,
      backgroundColor: `${colors.systemBlue}14`,
    },
    readerDialogueSpeaker: {
      color: colors.systemBlue,
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.7,
      textTransform: "uppercase",
    },
    readerDialogueText: {
      fontWeight: "700",
    },
    readerAnnotatedWord: {
      color: colors.systemBlue,
      fontWeight: "800",
      textDecorationLine: "underline",
    },
    readerInteraction: {
      gap: 12,
      marginTop: 8,
      padding: 16,
      borderRadius: 18,
      backgroundColor: colors.backgroundSecondary,
    },
    readerChoice: {
      minHeight: 42,
      justifyContent: "center",
      borderRadius: 14,
      paddingHorizontal: 12,
      paddingVertical: 9,
      backgroundColor: colors.backgroundTertiary,
    },
    readerChoiceSelected: {
      backgroundColor: `${colors.systemBlue}22`,
    },
    readerSavedAnswer: {
      padding: 14,
      borderRadius: 14,
      backgroundColor: `${colors.systemBlue}22`,
    },
    readerChoiceText: {
      color: colors.labelPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    readerFeedback: {
      gap: 10,
      marginTop: 4,
      padding: 14,
      borderRadius: 16,
      backgroundColor: `${colors.systemGreen}1f`,
    },
    readerComplete: {
      gap: 8,
      marginTop: 4,
      padding: 14,
      borderRadius: 16,
      backgroundColor: `${colors.systemPurple}1f`,
    },
    readerAudioBar: {
      position: "absolute",
      left: 16,
      right: 16,
      bottom: 24,
      flexDirection: "row",
      alignItems: "center",
      gap: 14,
      minHeight: 74,
      borderRadius: 22,
      paddingHorizontal: 16,
      backgroundColor: colors.glassBackground,
    },
    audioTrackTitle: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "800",
      marginBottom: 3,
    },
    audioTrackSubtitle: {
      color: colors.labelSecondary,
      fontSize: 12,
      fontWeight: "600",
    },
    audioPlayButton: {
      minWidth: 74,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 22,
      backgroundColor: colors.systemBlue,
    },
    audioPauseButton: { backgroundColor: colors.systemOrange },
    audioPlayButtonText: {
      color: "#ffffff",
      fontSize: 13,
      fontWeight: "900",
    },
    readerSheetScrim: {
      flex: 1,
      justifyContent: "flex-end",
      backgroundColor: "#00000040",
    },
    readerTranslationSheet: {
      gap: 10,
      borderTopLeftRadius: 28,
      borderTopRightRadius: 28,
      padding: 22,
      paddingBottom: 38,
      backgroundColor: colors.backgroundSecondary,
    },
    readerSheetHandle: {
      alignSelf: "center",
      width: 42,
      height: 5,
      borderRadius: 3,
      backgroundColor: colors.separator,
      marginBottom: 8,
    },
    translationSurface: {
      color: colors.labelPrimary,
      fontSize: 26,
      fontWeight: "900",
    },
    translationText: {
      color: colors.labelPrimary,
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 25,
    },
    dictionaryScreen: { flex: 1, paddingTop: 14 },
    dictionaryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      height: 42,
      marginHorizontal: 20,
      marginTop: 20,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: colors.backgroundSecondary,
    },
    searchIcon: { color: colors.labelSecondary, fontSize: 22 },
    searchInput: { flex: 1, color: colors.labelPrimary, fontSize: 15 },
    placeholder: { color: colors.labelTertiary },
    clearSearch: { color: colors.labelSecondary, fontSize: 24, lineHeight: 24 },
    filterViewport: { height: 46, overflow: "hidden", marginTop: 10 },
    filterRow: { alignItems: "center", gap: 6, paddingHorizontal: 20 },
    filterPill: {
      height: 34,
      justifyContent: "center",
      paddingHorizontal: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.separator,
      borderRadius: 17,
      backgroundColor: colors.backgroundSecondary,
    },
    activeFilterPill: { backgroundColor: colors.systemBlue },
    filterText: {
      color: colors.labelSecondary,
      fontSize: 13,
      fontWeight: "700",
    },
    activeFilterText: { color: "#ffffff" },
    queueFilterBar: {
      flexDirection: "row",
      marginHorizontal: 20,
      marginTop: 12,
      marginBottom: 10,
      padding: 2,
      borderRadius: 10,
      backgroundColor: `${colors.labelSecondary}14`,
    },
    queueFilterOption: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 30,
      borderRadius: 8,
    },
    activeQueueFilterOption: { backgroundColor: colors.backgroundSecondary },
    queueFilterText: {
      color: colors.labelSecondary,
      fontSize: 11,
      fontWeight: "700",
    },
    activeQueueFilterText: { color: colors.labelPrimary },
    counterText: {
      color: colors.labelSecondary,
      fontSize: 12,
      fontWeight: "600",
      paddingHorizontal: 20,
      paddingBottom: 8,
    },
    wordList: { paddingHorizontal: 20, paddingBottom: 108 },
    wordRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 72,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
      backgroundColor: colors.backgroundSecondary,
    },
    wordHeading: {
      flexDirection: "row",
      alignItems: "baseline",
      gap: 7,
      marginBottom: 6,
    },
    wordTitle: {
      color: colors.labelPrimary,
      fontSize: 17,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    partOfSpeech: { color: colors.labelSecondary, fontSize: 12 },
    phonetics: { color: colors.systemOrange, fontSize: 13 },
    levelBadge: {
      minWidth: 34,
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 9,
    },
    levelA1: { backgroundColor: `${colors.systemGreen}22` },
    levelA2: { backgroundColor: `${colors.systemBlue}22` },
    levelB1: { backgroundColor: `${colors.systemOrange}22` },
    levelB2: { backgroundColor: `${colors.systemPurple}22` },
    levelC1: { backgroundColor: `${colors.systemRed}22` },
    levelC2: { backgroundColor: `${colors.systemRed}22` },
    levelBadgeText: {
      color: colors.labelPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    stateMessage: { alignItems: "center", gap: 6, padding: 36 },
    stateMessageTitle: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "700",
    },
    sheetContent: {
      flex: 1,
      gap: 12,
      padding: 20,
      paddingBottom: 0,
      backgroundColor: colors.backgroundSecondary,
    },
    detailsHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      marginTop: 2,
    },
    detailsTitle: {
      color: colors.labelPrimary,
      fontSize: 28,
      fontWeight: "700",
      letterSpacing: -0.5,
      marginBottom: 5,
    },
    closeButton: { color: colors.labelSecondary, fontSize: 30, lineHeight: 30 },
    sheetDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.separator,
    },
    detailsText: { color: colors.labelPrimary, fontSize: 15, lineHeight: 24 },
    exampleText: { color: colors.labelPrimary, fontSize: 15, lineHeight: 23 },
  });
}

// AppStyleSheet is the exact style-key contract consumed by presentation components.
export type AppStyleSheet = ReturnType<typeof createAppStylesImpl>;

// createStyles builds the themed StyleSheet consumed through the AppStyles contract.
export function createStyles(colors: AppColors): AppStyleSheet {
  return createAppStylesImpl(colors);
}
