import { StyleSheet } from "react-native";

import type { AppColors } from "@presentation/theme/tokens";
import {
  fontFamilies,
  getFloatingTabBarContentPadding,
  motion,
  radii,
  shadows,
} from "@presentation/theme";

// floatingTabContentPadding is the shared no-inset baseline for tab-safe scroll endings.
const floatingTabContentPadding: number = getFloatingTabBarContentPadding(0);

// createAppStylesImpl keeps the exact StyleSheet key contract inferred in one place.
function createAppStylesImpl(colors: AppColors) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.backgroundPrimary },
    routeSafeArea: { flex: 1, backgroundColor: "transparent" },
    flex: { flex: 1 },
    authKeyboardView: { flex: 1 },
    authScrollContent: {
      flexGrow: 1,
      paddingVertical: 28,
    },
    bootstrapScreen: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
      padding: 24,
    },
    authContent: {
      width: "100%",
      maxWidth: 520,
      alignSelf: "center",
      marginVertical: "auto",
      gap: 28,
      padding: 20,
    },
    authFormKeyboardRegion: { width: "100%" },
    authHeader: { gap: 8 },
    authTitle: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.displayHeavy,
      fontSize: 36,
      letterSpacing: -0.9,
      lineHeight: 46,
      paddingVertical: 2,
    },
    authSubtitle: {
      color: colors.labelSecondary,
      fontFamily: fontFamilies.body,
      fontSize: 15,
      lineHeight: 24,
    },
    authCard: {
      gap: 20,
      padding: 22,
    },
    authModeRow: {
      flexDirection: "row",
      gap: 6,
      padding: 3,
      borderRadius: 14,
      backgroundColor: colors.backgroundTertiary,
    },
    authModeButton: {
      flex: 1,
      minHeight: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 11,
    },
    authModeButtonActive: { backgroundColor: colors.systemBlue },
    authModeButtonText: {
      color: colors.labelSecondary,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 13,
    },
    authModeButtonTextActive: { color: "#ffffff" },
    authMessage: {
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    authErrorMessage: { backgroundColor: `${colors.systemRed}1f` },
    authSuccessMessage: { backgroundColor: `${colors.systemGreen}1f` },
    authMessageText: {
      color: colors.labelPrimary,
      fontSize: 13,
      fontWeight: "600",
      lineHeight: 19,
    },
    syncErrorBox: {
      borderRadius: 14,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: `${colors.systemRed}1f`,
    },
    syncErrorText: {
      color: colors.labelPrimary,
      fontSize: 12,
      fontWeight: "600",
      lineHeight: 18,
    },
    screenContent: {
      gap: 22,
      padding: 20,
      paddingBottom: floatingTabContentPadding,
    },
    readerContent: {
      gap: 14,
      padding: 12,
      paddingBottom: floatingTabContentPadding,
    },
    modalScreen: { flex: 1, backgroundColor: colors.backgroundPrimary },
    modalContent: { gap: 14, padding: 20, paddingTop: 14, paddingBottom: 36 },
    modalHeader: {
      minHeight: 74,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
      paddingHorizontal: 16,
      paddingTop: 14,
      paddingBottom: 10,
      backgroundColor: colors.backgroundPrimary,
    },
    modalActions: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      flexShrink: 0,
    },
    modalTextButton: {
      minWidth: 72,
      minHeight: 44,
      alignItems: "center",
      justifyContent: "center",
    },
    modalTitle: {
      flex: 1,
      color: colors.labelPrimary,
      fontFamily: fontFamilies.displayHeavy,
      fontSize: 24,
      letterSpacing: -0.3,
      lineHeight: 30,
    },
    modalCancel: { color: colors.systemBlue, fontSize: 15, fontWeight: "600" },
    modalSave: { color: colors.systemBlue, fontSize: 15, fontWeight: "800" },
    modalPrimaryAction: {
      minWidth: 112,
      minHeight: 40,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    modalSecondaryAction: {
      minWidth: 72,
      minHeight: 40,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    modalPrimaryActionText: {
      color: "#ffffff",
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 13,
    },
    modalSecondaryActionText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 13,
    },
    homeHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 12,
      marginBottom: 2,
    },
    homeTitleBlock: {
      gap: 8,
      minWidth: 0,
      width: "100%",
    },
    homeTitle: {
      flexShrink: 1,
      fontSize: 36,
      letterSpacing: -1,
      lineHeight: 46,
    },
    homeTitleAccent: {
      width: 56,
      height: 6,
      borderRadius: radii.pill,
      backgroundColor: colors.systemPink,
      shadowColor: colors.systemPink,
      shadowOffset: { width: 0, height: 5 },
      shadowOpacity: 0.38,
      shadowRadius: 12,
    },
    readerTitleBlock: {
      minWidth: 0,
      width: "100%",
      gap: 3,
    },
    readerBadge: {
      alignSelf: "flex-start",
      overflow: "hidden",
      borderRadius: radii.pill,
      backgroundColor: `${colors.systemPurple}2b`,
      color: colors.systemPurple,
      fontSize: 11,
      fontWeight: "900",
      paddingHorizontal: 12,
      paddingVertical: 6,
    },
    seriesDetailsHeader: {
      gap: 6,
      minWidth: 0,
      paddingVertical: 2,
      width: "100%",
    },
    largeTitle: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.displayHeavy,
      flexShrink: 1,
      fontSize: 31,
      letterSpacing: -0.8,
      lineHeight: 40,
      paddingVertical: 2,
    },
    avatar: {
      width: 42,
      height: 42,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 21,
      backgroundColor: colors.systemBlue,
    },
    avatarText: { color: "#ffffff", fontSize: 13, fontWeight: "700" },
    appCategory: {
      color: colors.systemBlue,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 11,
      letterSpacing: 0.7,
      marginBottom: 3,
    },
    roundActionButton: {
      width: 46,
      height: 46,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 23,
      backgroundColor: colors.systemBlue,
      ...shadows.clay,
    },
    roundActionText: {
      color: "#ffffff",
      fontSize: 28,
      fontWeight: "600",
      lineHeight: 30,
    },
    secondaryText: {
      color: colors.labelSecondary,
      fontFamily: fontFamilies.body,
      fontSize: 13,
      lineHeight: 19,
    },
    goalCard: {
      borderRadius: radii.xl,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      backgroundColor: colors.bubbleSurface,
      padding: 18,
      ...shadows.soft,
    },
    sectionLabel: {
      color: colors.systemPurple,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 11,
      letterSpacing: 0.7,
      marginTop: 6,
    },
    actionList: {
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.lg,
      backgroundColor: colors.bubbleSurfaceMuted,
      ...shadows.soft,
    },
    seriesList: {
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.lg,
      backgroundColor: colors.bubbleSurfaceMuted,
      ...shadows.soft,
    },
    emptySeriesPanel: {
      gap: 8,
      minHeight: 104,
      justifyContent: "center",
      borderRadius: radii.xl,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      backgroundColor: colors.bubbleSurface,
      ...shadows.soft,
    },
    episodeList: {
      gap: 12,
    },
    episodeCard: {
      gap: 12,
      padding: 16,
      borderLeftWidth: 3,
      borderLeftColor: colors.systemTeal,
      borderRadius: 26,
    },
    episodeCardContent: {
      gap: 4,
      minWidth: 0,
    },
    episodeCardTitle: {
      flexShrink: 1,
      lineHeight: 23,
      minHeight: 46,
    },
    episodeCardSummary: {
      flexShrink: 1,
      lineHeight: 19,
      minHeight: 38,
    },
    episodeCardActions: {
      flexDirection: "row",
      alignItems: "center",
      flexShrink: 0,
      gap: 10,
    },
    episodeCompactDelete: {
      minHeight: 38,
      borderRadius: radii.lg,
      paddingHorizontal: 16,
    },
    seriesRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 104,
      paddingHorizontal: 14,
      paddingVertical: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
    },
    seriesMeta: {
      overflow: "hidden",
      borderRadius: radii.pill,
      backgroundColor: `${colors.systemBlue}22`,
      color: colors.systemBlue,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 11,
      paddingHorizontal: 9,
      paddingVertical: 3,
    },
    seriesPremise: {
      color: colors.labelSecondary,
      fontFamily: fontFamilies.body,
      fontSize: 12,
      lineHeight: 17,
      marginTop: 3,
    },
    smallPrimaryButton: {
      minHeight: 42,
      justifyContent: "center",
      borderRadius: radii.md,
      paddingHorizontal: 16,
      backgroundColor: colors.systemBlue,
      ...shadows.clay,
    },
    smallPrimaryButtonText: {
      color: "#ffffff",
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 13,
    },
    secondarySmallButton: {
      minHeight: 42,
      justifyContent: "center",
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.md,
      paddingHorizontal: 16,
      backgroundColor: colors.bubbleSurfaceMuted,
    },
    secondarySmallButtonText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyBold,
      fontSize: 13,
    },
    destructiveIconButton: {
      minHeight: 34,
      justifyContent: "center",
      borderRadius: 12,
      paddingHorizontal: 11,
      borderWidth: 1,
      borderColor: `${colors.systemRed}35`,
      backgroundColor: `${colors.systemRed}16`,
    },
    destructiveIconText: {
      color: colors.systemRed,
      fontSize: 12,
      fontWeight: "800",
    },
    actionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 76,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
    },
    actionIcon: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 12,
    },
    blueIcon: { backgroundColor: colors.systemBlue },
    purpleIcon: { backgroundColor: colors.systemPurple },
    orangeIcon: { backgroundColor: colors.systemOrange },
    actionIconText: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
    actionTitle: {
      color: colors.labelPrimary,
      flexShrink: 1,
      fontFamily: fontFamilies.display,
      fontSize: 15,
      lineHeight: 23,
      marginBottom: 3,
    },
    rowChevron: { color: colors.labelTertiary, fontSize: 28 },
    pressed: { opacity: motion.pressedOpacity },
    settingsCard: {
      gap: 14,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.xl,
      backgroundColor: colors.bubbleSurface,
      ...shadows.soft,
    },
    settingsCompactCard: {
      gap: 10,
      padding: 14,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.xl,
      backgroundColor: colors.bubbleSurface,
      ...shadows.soft,
    },
    accountCompactHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 10,
    },
    accountStatusText: {
      color: colors.labelSecondary,
      fontFamily: fontFamilies.body,
      fontSize: 12,
      lineHeight: 17,
    },
    accountActionRow: {
      flexDirection: "row",
      gap: 8,
    },
    accountActionButton: {
      minHeight: 38,
      paddingHorizontal: 14,
      paddingVertical: 8,
    },
    settingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    settingToggle: {
      flexShrink: 0,
    },
    settingValue: {
      overflow: "hidden",
      borderRadius: 99,
      backgroundColor: `${colors.systemBlue}1f`,
      color: colors.systemBlue,
      fontSize: 12,
      fontWeight: "800",
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    settingsDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.separator,
      marginVertical: 4,
    },
    settingMeter: { gap: 10 },
    sliderControl: {
      height: 40,
      width: '100%',
    },
    choiceRow: {
      flexDirection: "row",
      flexWrap: "wrap",
      gap: 3,
      backgroundColor: colors.backgroundTertiary,
      padding: 3,
      borderRadius: radii.xl,
    },
    choiceRowSingle: {
      flexDirection: "row",
      width: "100%",
      backgroundColor: colors.backgroundTertiary,
      padding: 3,
      borderRadius: radii.xl,
    },
    choiceRowWrapped: {
      flexDirection: "row",
      flexWrap: "wrap",
      width: "100%",
      gap: 3,
      backgroundColor: colors.backgroundTertiary,
      padding: 3,
      borderRadius: radii.lg,
    },
    goalChoice: {
      flex: 1,
      minWidth: 48,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.lg,
      paddingHorizontal: 10,
      paddingVertical: 9,
      backgroundColor: "transparent",
    },
    goalChoiceSingleContainer: {
      flex: 1,
    },
    goalChoiceSingle: {
      flex: 1,
      minHeight: 38,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.lg,
      paddingHorizontal: 10,
      paddingVertical: 9,
      backgroundColor: "transparent",
    },
    goalChoiceWrappedContainer: {
      flexGrow: 1,
      flexBasis: "45%",
    },
    goalChoiceWrapped: {
      flex: 1,
      minHeight: 38,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.lg,
      paddingHorizontal: 10,
      paddingVertical: 9,
      backgroundColor: "transparent",
    },
    activeGoalChoice: { backgroundColor: colors.bubbleSurfaceRaised, ...shadows.clay },
    activeGoalChoiceWrapped: {
      backgroundColor: colors.bubbleSurfaceRaised,
      ...shadows.clay,
    },
    goalChoiceText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyBold,
      fontSize: 15,
      textAlign: "center",
    },
    goalChoiceTextWrapped: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyBold,
      fontSize: 15,
      textAlign: "center",
    },
    activeGoalChoiceText: { color: colors.labelPrimary },
    activeGoalChoiceTextWrapped: {
      color: colors.labelPrimary,
    },
    formGroup: { gap: 7 },
    formLabelRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    formInput: {
      minHeight: 50,
      borderWidth: 1,
      borderColor: colors.pillBorder,
      borderRadius: radii.md,
      paddingHorizontal: 16,
      backgroundColor: colors.backgroundTertiary,
      color: colors.labelPrimary,
      fontFamily: fontFamilies.body,
      fontSize: 15,
    },
    formTextArea: {
      height: 96,
      paddingTop: 13,
      lineHeight: 21,
    },
    formCompactTextArea: {
      height: 58,
      paddingTop: 13,
      lineHeight: 21,
    },
    formErrorText: {
      color: colors.systemRed,
      fontSize: 12,
      fontWeight: "700",
      lineHeight: 17,
      paddingHorizontal: 4,
    },
    formHelperText: {
      color: colors.labelSecondary,
      fontSize: 12,
      lineHeight: 17,
      paddingHorizontal: 4,
    },
    setupAiSourceLabel: {
      color: colors.systemTeal,
      flexShrink: 1,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 9,
      letterSpacing: 0.45,
      textAlign: "right",
    },
    setupReadOnlyInput: {
      opacity: 0.72,
    },
    setupDraftHeader: {
      gap: 3,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderTopColor: colors.separator,
      paddingTop: 15,
    },
    setupDraftTitle: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.display,
      fontSize: 18,
      lineHeight: 24,
    },
    setupBuildAction: {
      minHeight: 50,
      alignSelf: "stretch",
      justifyContent: "center",
    },
    setupBuildActionText: {
      color: "#ffffff",
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 14,
      textAlign: "center",
    },
    setupUndoAction: {
      minHeight: 44,
      alignSelf: "stretch",
      justifyContent: "center",
    },
    setupUndoActionText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyBold,
      fontSize: 13,
      textAlign: "center",
    },
    practiceCard: {
      gap: 12,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.xl,
      backgroundColor: colors.bubbleSurface,
      ...shadows.soft,
    },
    practiceWord: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.displayHeavy,
      fontSize: 34,
      letterSpacing: -0.6,
    },
    practiceActions: { flexDirection: "row", gap: 10 },
    primaryButton: {
      minHeight: 52,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.lg,
      paddingHorizontal: 18,
      backgroundColor: colors.systemBlue,
      ...shadows.clay,
    },
    primaryButtonText: {
      color: "#ffffff",
      flexShrink: 1,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 15,
      textAlign: "center",
    },
    secondaryButton: {
      flex: 1,
      minHeight: 52,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: radii.lg,
      paddingHorizontal: 18,
      backgroundColor: colors.backgroundTertiary,
    },
    secondaryButtonText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyBold,
      fontSize: 15,
    },
    disabledControl: { opacity: 0.55 },
    genreRow: {
      minHeight: 54,
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      borderRadius: 14,
      paddingHorizontal: 14,
      backgroundColor: colors.backgroundTertiary,
    },
    activeGenreRow: { backgroundColor: `${colors.systemBlue}1f` },
    offlineNotice: {
      gap: 6,
      marginTop: 14,
      padding: 14,
      borderRadius: 16,
      backgroundColor: `${colors.systemOrange}1f`,
    },
    readerRecap: {
      gap: 8,
      padding: 16,
      borderRadius: 18,
      backgroundColor: colors.bubbleSurfaceMuted,
    },
    readerStory: {
      gap: 8,
      paddingVertical: 4,
    },
    readerSentence: {
      borderRadius: 12,
      paddingHorizontal: 2,
      paddingVertical: 2,
    },
    readerSentenceActive: {
      backgroundColor: `${colors.systemBlue}1f`,
      opacity: 1,
    },
    readerSentenceDimmed: {
      backgroundColor: "transparent",
      opacity: 0.48,
    },
    readerSentenceRest: {
      backgroundColor: "transparent",
      opacity: 1,
    },
    readerEpisodeBlock: {
      gap: 8,
      paddingBottom: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
    },
    readerEpisodeHeading: {
      gap: 5,
      paddingHorizontal: 4,
    },
    readerEpisodeBadge: {
      color: colors.systemPurple,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 13,
      fontWeight: '900',
      letterSpacing: 0.9,
      lineHeight: 18,
      marginTop: 4,
    },
    readerEpisodeTitle: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.display,
      fontSize: 20,
      lineHeight: 28,
    },
    readerSentenceText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyRegular,
      fontSize: 16,
      lineHeight: 26,
    },
    readerDialogueFrame: {
      gap: 8,
    },
    readerDialogueRow: {
      flexDirection: 'row',
      alignItems: 'flex-start',
      gap: 8,
    },
    readerLearnerDialogueRow: {
      flexDirection: 'row-reverse',
    },
    readerDialogueAvatar: {
      width: 28,
      height: 28,
      alignItems: 'center',
      justifyContent: 'center',
      borderRadius: 14,
    },
    readerDialogueAvatarText: {
      color: '#ffffff',
      fontSize: 11,
      fontWeight: '700',
    },
    readerDialogueContent: {
      flex: 1,
      maxWidth: '86%',
      gap: 2,
    },
    readerLearnerDialogueContent: {
      alignItems: 'flex-end',
    },
    readerDialogueSpeakerName: {
      fontSize: 9,
      fontWeight: '700',
      marginLeft: 1,
      textTransform: 'uppercase',
    },
    readerLearnerDialogueSpeakerName: {
      marginLeft: 0,
      marginRight: 1,
      textAlign: 'right',
    },
    readerDialogueBubbleFrame: {
      alignSelf: 'flex-start',
      borderWidth: 1,
      borderRadius: 12,
      borderTopLeftRadius: 4,
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    readerLearnerDialogueBubbleFrame: {
      alignSelf: 'flex-end',
      borderTopLeftRadius: 12,
      borderTopRightRadius: 4,
    },
    readerNarrativeSentenceFrame: {
      marginLeft: 36,
      paddingHorizontal: 2,
      paddingVertical: 4,
    },
    readerDialogueBubble: {
      alignSelf: "flex-start",
      maxWidth: "94%",
      gap: 5,
      borderWidth: 1,
      borderLeftWidth: 3,
      borderColor: `${colors.systemBlue}22`,
      borderLeftColor: colors.systemBlue,
      borderRadius: radii.lg,
      borderTopLeftRadius: 6,
      paddingHorizontal: 14,
      paddingVertical: 12,
      backgroundColor: `${colors.systemBlue}14`,
      ...shadows.soft,
    },
    readerDialogueSpeaker: {
      color: colors.systemBlue,
      fontSize: 11,
      fontWeight: "900",
      letterSpacing: 0.7,
      textTransform: "uppercase",
    },
    readerDialogueText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyRegular,
      fontSize: 15,
      lineHeight: 24,
    },
    readerAnnotatedWord: {
      color: colors.systemBlue,
      textDecorationLine: "underline",
    },
    readerInteraction: {
      gap: 8,
      marginTop: 8,
      padding: 16,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.lg,
      backgroundColor: colors.bubbleSurface,
      ...shadows.soft,
    },
    readerChoice: {
      minHeight: 48,
      justifyContent: "center",
      borderRadius: radii.md,
      paddingHorizontal: 14,
      paddingVertical: 11,
      backgroundColor: colors.backgroundTertiary,
    },
    readerChoiceSelected: {
      backgroundColor: `${colors.systemBlue}22`,
    },
    readerSavedAnswer: {
      alignSelf: "flex-end",
      maxWidth: "86%",
      paddingHorizontal: 12,
      paddingVertical: 8,
      borderWidth: 1,
      borderColor: `${colors.systemGreen}33`,
      borderRadius: 12,
      borderTopRightRadius: 4,
      backgroundColor: `${colors.systemGreen}14`,
      shadowColor: colors.systemGreen,
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 6,
    },
    readerNarrativeAnswer: {
      marginLeft: 36,
      paddingVertical: 4,
      paddingHorizontal: 2,
      backgroundColor: "transparent",
    },
    readerNarrativeAnswerText: {
      color: colors.systemBlue,
      fontSize: 13,
      fontStyle: "italic",
      fontWeight: "500",
      lineHeight: 21,
    },
    readerSavedAnswerText: {
      color: colors.labelPrimary,
      fontSize: 13,
      fontWeight: "400",
      lineHeight: 21,
    },
    readerChoiceText: {
      color: colors.labelPrimary,
      fontSize: 13,
      fontWeight: "800",
    },
    readerFeedback: {
      gap: 8,
      marginTop: 4,
      padding: 12,
      borderRadius: 12,
      backgroundColor: `${colors.systemGreen}1f`,
    },
    readerComplete: {
      gap: 8,
      marginTop: 4,
      padding: 14,
      borderRadius: 16,
      backgroundColor: `${colors.systemPurple}1f`,
    },
    readerTranslationContent: {
      gap: 10,
    },
    translationText: {
      color: colors.labelPrimary,
      fontSize: 18,
      fontWeight: "700",
      lineHeight: 25,
    },
    dictionaryScreen: { flex: 1, paddingTop: 20 },
    dictionaryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 12,
      paddingHorizontal: 20,
    },
    dictionaryWorkspace: {
      flex: 1,
      minHeight: 0,
      position: "relative",
    },
    dictionarySearchOverlay: {
      left: 0,
      position: "absolute",
      right: 0,
      top: 0,
      zIndex: 20,
    },
    dictionaryAndroidBottomFade: {
      position: "absolute",
      left: 0,
      right: 0,
      bottom: 0,
      height: 132,
      zIndex: 10,
    },
    searchBarShell: {
      height: 54,
      marginHorizontal: 20,
      marginTop: 14,
      borderRadius: radii.lg,
      ...shadows.soft,
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      height: 54,
      overflow: "hidden",
      paddingHorizontal: 10,
      borderRadius: radii.lg,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      backgroundColor: colors.bubbleSurface,
    },
    searchBarMaterial: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    searchIcon: {
      color: colors.labelSecondary,
      fontSize: 22,
      lineHeight: 24,
    },
    searchInput: {
      flex: 1,
      color: colors.labelPrimary,
      fontFamily: fontFamilies.body,
      fontSize: 15,
      minWidth: 0,
      paddingVertical: 0,
    },
    placeholder: { color: colors.labelTertiary },
    clearSearch: { color: colors.labelSecondary, fontSize: 24, lineHeight: 24 },
    queueFilterBar: {
      flexDirection: "row",
      marginHorizontal: 20,
      marginTop: 12,
      marginBottom: 10,
      padding: 2,
      borderRadius: 10,
      backgroundColor: `${colors.labelSecondary}14`,
    },
    queueFilterOption: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 30,
      borderRadius: 8,
    },
    activeQueueFilterOption: { backgroundColor: colors.backgroundSecondary },
    queueFilterText: {
      color: colors.labelSecondary,
      fontSize: 11,
      fontWeight: "700",
    },
    activeQueueFilterText: { color: colors.labelPrimary },
    dictionaryListViewport: {
      flex: 1,
      minHeight: 0,
    },
    dictionaryScrollViewport: {
      flex: 1,
      minHeight: 0,
      position: "relative",
    },
    dictionaryStateViewport: {
      flex: 1,
      paddingTop: 82,
    },
    wordList: {
      gap: 5,
      paddingHorizontal: 20,
      paddingTop: 82,
      paddingBottom: floatingTabContentPadding,
    },
    wordRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 10,
      height: 62,
      paddingHorizontal: 13,
      overflow: "hidden",
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.md,
      backgroundColor: colors.bubbleSurfaceMuted,
    },
    wordRowGradient: {
      position: "absolute",
      top: 0,
      right: 0,
      bottom: 0,
      left: 0,
    },
    wordLevelRail: {
      width: 3,
      height: 28,
      borderRadius: radii.pill,
    },
    wordLevelA1: { backgroundColor: colors.systemGreen },
    wordLevelA2: { backgroundColor: colors.systemTeal },
    wordLevelB1: { backgroundColor: colors.systemOrange },
    wordLevelB2: { backgroundColor: colors.systemPurple },
    wordLevelC1: { backgroundColor: colors.systemPink },
    wordLevelC2: { backgroundColor: colors.systemBlue },
    wordHeading: {
      flexDirection: "row",
      alignItems: "baseline",
      gap: 6,
      minWidth: 0,
      marginBottom: 3,
    },
    wordTitle: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.display,
      fontSize: 16,
      lineHeight: 21,
      letterSpacing: -0.2,
      flexShrink: 1,
    },
    partOfSpeech: {
      color: colors.labelSecondary,
      fontSize: 12,
      flexShrink: 1,
    },
    phonetics: { color: colors.systemOrange, fontSize: 13 },
    levelBadge: {
      minWidth: 34,
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 9,
    },
    levelA1: { backgroundColor: `${colors.systemGreen}22` },
    levelA2: { backgroundColor: `${colors.systemBlue}22` },
    levelB1: { backgroundColor: `${colors.systemOrange}22` },
    levelB2: { backgroundColor: `${colors.systemPurple}22` },
    levelC1: { backgroundColor: `${colors.systemRed}22` },
    levelC2: { backgroundColor: `${colors.systemRed}22` },
    levelBadgeText: {
      color: colors.labelPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    stateMessage: { alignItems: "center", gap: 6, padding: 36 },
    stateMessageTitle: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "700",
    },
    readerInteractionError: {
      alignItems: "flex-start",
      gap: 10,
      marginBottom: 14,
      padding: 14,
      borderWidth: 1,
      borderColor: `${colors.systemOrange}30`,
      borderRadius: radii.md,
      backgroundColor: colors.badgeWarningSurface,
    },
    readerInteractionErrorText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.bodyBold,
      fontSize: 13,
      lineHeight: 19,
    },
    readerRetryButton: {
      minHeight: 40,
      alignSelf: "flex-start",
      alignItems: "center",
      justifyContent: "center",
      paddingHorizontal: 16,
      borderWidth: 1,
      borderColor: colors.pillBorder,
      borderRadius: radii.pill,
      backgroundColor: colors.pillSurface,
    },
    readerRetryButtonText: {
      color: colors.systemBlue,
      fontFamily: fontFamilies.bodyHeavy,
      fontSize: 13,
      lineHeight: 18,
    },
    sheetContent: {
      flex: 1,
      gap: 12,
      padding: 20,
      paddingBottom: 0,
      backgroundColor: colors.backgroundSecondary,
    },
    dictionarySheetContent: {
      gap: 12,
      paddingTop: 2,
      paddingBottom: 0,
    },
    detailsHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      marginTop: 2,
    },
    detailsTitle: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.displayHeavy,
      fontSize: 28,
      letterSpacing: -0.4,
      marginBottom: 5,
    },
    closeButton: { color: colors.labelSecondary, fontSize: 30, lineHeight: 30 },
    sheetDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.separator,
    },
    detailsText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.body,
      fontSize: 15,
      lineHeight: 24,
    },
    exampleText: {
      color: colors.labelPrimary,
      fontFamily: fontFamilies.body,
      fontSize: 15,
      lineHeight: 23,
    },
    flexOne: { flex: 1 },
    homeErrorStatus: {
      marginBottom: 8,
    },
    setupSectionCard: {
      gap: 13,
      padding: 18,
      borderWidth: 1,
      borderColor: colors.bubbleBorder,
      borderRadius: radii.xl,
      backgroundColor: colors.bubbleSurface,
      ...shadows.soft,
    },
  });
}

// AppStyleSheet is the exact style-key contract consumed by presentation components.
export type AppStyleSheet = ReturnType<typeof createAppStylesImpl>;

// createStyles builds the themed StyleSheet consumed through the AppStyles contract.
export function createStyles(colors: AppColors): AppStyleSheet {
  return createAppStylesImpl(colors);
}
