import { StyleSheet } from "react-native";

import type { AppColors } from "@presentation/theme/tokens";

export function createStyles(colors: AppColors) {
  return StyleSheet.create({
    safeArea: { flex: 1, backgroundColor: colors.backgroundPrimary },
    flex: { flex: 1 },
    screenContent: { gap: 18, padding: 20, paddingBottom: 118 },
    homeHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      marginTop: 8,
    },
    largeTitle: {
      color: colors.labelPrimary,
      fontSize: 28,
      fontWeight: "700",
      letterSpacing: -0.6,
    },
    avatar: {
      width: 42,
      height: 42,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 21,
      backgroundColor: colors.systemBlue,
    },
    avatarText: { color: "#ffffff", fontSize: 13, fontWeight: "700" },
    secondaryText: {
      color: colors.labelSecondary,
      fontSize: 13,
      lineHeight: 19,
    },
    goalCard: {
      borderRadius: 22,
      backgroundColor: colors.backgroundSecondary,
      padding: 18,
    },
    sectionLabel: {
      color: colors.labelSecondary,
      fontSize: 11,
      fontWeight: "700",
      letterSpacing: 0.7,
      marginTop: 6,
    },
    actionList: {
      overflow: "hidden",
      borderRadius: 20,
      backgroundColor: colors.backgroundSecondary,
    },
    actionRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 76,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
    },
    actionIcon: {
      width: 40,
      height: 40,
      alignItems: "center",
      justifyContent: "center",
      borderRadius: 12,
    },
    blueIcon: { backgroundColor: colors.systemBlue },
    purpleIcon: { backgroundColor: colors.systemPurple },
    orangeIcon: { backgroundColor: colors.systemOrange },
    actionIconText: { color: "#ffffff", fontSize: 14, fontWeight: "800" },
    actionTitle: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "700",
      marginBottom: 3,
    },
    rowChevron: { color: colors.labelTertiary, fontSize: 28 },
    pressed: { opacity: 0.78, transform: [{ scale: 0.98 }] },
    settingsCard: {
      gap: 14,
      padding: 16,
      borderRadius: 20,
      backgroundColor: colors.backgroundSecondary,
    },
    settingRow: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      gap: 12,
    },
    settingValue: {
      overflow: "hidden",
      borderRadius: 99,
      backgroundColor: `${colors.systemBlue}1f`,
      color: colors.systemBlue,
      fontSize: 12,
      fontWeight: "800",
      paddingHorizontal: 10,
      paddingVertical: 6,
    },
    cefrSegmentedControl: { height: 38 },
    settingMeter: { gap: 10 },
    meterTrack: {
      height: 6,
      overflow: "hidden",
      borderRadius: 3,
      backgroundColor: colors.backgroundTertiary,
    },
    meterFill: {
      height: 6,
      borderRadius: 3,
      backgroundColor: colors.systemBlue,
    },
    dictionaryScreen: { flex: 1, paddingTop: 14 },
    dictionaryHeader: {
      flexDirection: "row",
      alignItems: "center",
      justifyContent: "space-between",
      paddingHorizontal: 20,
    },
    searchBar: {
      flexDirection: "row",
      alignItems: "center",
      gap: 8,
      height: 42,
      marginHorizontal: 20,
      marginTop: 20,
      paddingHorizontal: 12,
      borderRadius: 12,
      backgroundColor: colors.backgroundSecondary,
    },
    searchIcon: { color: colors.labelSecondary, fontSize: 22 },
    searchInput: { flex: 1, color: colors.labelPrimary, fontSize: 15 },
    placeholder: { color: colors.labelTertiary },
    clearSearch: { color: colors.labelSecondary, fontSize: 24, lineHeight: 24 },
    filterViewport: { height: 46, overflow: "hidden", marginTop: 10 },
    filterRow: { alignItems: "center", gap: 6, paddingHorizontal: 20 },
    filterPill: {
      height: 34,
      justifyContent: "center",
      paddingHorizontal: 14,
      borderWidth: StyleSheet.hairlineWidth,
      borderColor: colors.separator,
      borderRadius: 17,
      backgroundColor: colors.backgroundSecondary,
    },
    activeFilterPill: { backgroundColor: colors.systemBlue },
    filterText: {
      color: colors.labelSecondary,
      fontSize: 13,
      fontWeight: "700",
    },
    activeFilterText: { color: "#ffffff" },
    queueFilterBar: {
      flexDirection: "row",
      marginHorizontal: 20,
      marginTop: 12,
      marginBottom: 10,
      padding: 2,
      borderRadius: 10,
      backgroundColor: `${colors.labelSecondary}14`,
    },
    queueFilterOption: {
      flex: 1,
      alignItems: "center",
      justifyContent: "center",
      minHeight: 30,
      borderRadius: 8,
    },
    activeQueueFilterOption: { backgroundColor: colors.backgroundSecondary },
    queueFilterText: {
      color: colors.labelSecondary,
      fontSize: 11,
      fontWeight: "700",
    },
    activeQueueFilterText: { color: colors.labelPrimary },
    counterText: {
      color: colors.labelSecondary,
      fontSize: 12,
      fontWeight: "600",
      paddingHorizontal: 20,
      paddingBottom: 8,
    },
    wordList: { paddingHorizontal: 20, paddingBottom: 108 },
    wordRow: {
      flexDirection: "row",
      alignItems: "center",
      gap: 12,
      minHeight: 72,
      paddingHorizontal: 14,
      borderBottomWidth: StyleSheet.hairlineWidth,
      borderBottomColor: colors.separator,
      backgroundColor: colors.backgroundSecondary,
    },
    wordHeading: {
      flexDirection: "row",
      alignItems: "baseline",
      gap: 7,
      marginBottom: 6,
    },
    wordTitle: {
      color: colors.labelPrimary,
      fontSize: 17,
      fontWeight: "700",
      letterSpacing: -0.2,
    },
    partOfSpeech: { color: colors.labelSecondary, fontSize: 12 },
    phonetics: { color: colors.systemOrange, fontSize: 13 },
    levelBadge: {
      minWidth: 34,
      alignItems: "center",
      paddingHorizontal: 8,
      paddingVertical: 6,
      borderRadius: 9,
    },
    levelA1: { backgroundColor: `${colors.systemGreen}22` },
    levelA2: { backgroundColor: `${colors.systemBlue}22` },
    levelB1: { backgroundColor: `${colors.systemOrange}22` },
    levelB2: { backgroundColor: `${colors.systemPurple}22` },
    levelC1: { backgroundColor: `${colors.systemRed}22` },
    levelC2: { backgroundColor: `${colors.systemRed}22` },
    levelBadgeText: {
      color: colors.labelPrimary,
      fontSize: 11,
      fontWeight: "800",
    },
    stateMessage: { alignItems: "center", gap: 6, padding: 36 },
    stateMessageTitle: {
      color: colors.labelPrimary,
      fontSize: 15,
      fontWeight: "700",
    },
    sheetContent: {
      flex: 1,
      gap: 12,
      padding: 20,
      paddingBottom: 0,
      backgroundColor: colors.backgroundSecondary,
    },
    detailsHeader: {
      flexDirection: "row",
      alignItems: "flex-start",
      justifyContent: "space-between",
      marginTop: 2,
    },
    detailsTitle: {
      color: colors.labelPrimary,
      fontSize: 28,
      fontWeight: "700",
      letterSpacing: -0.5,
      marginBottom: 5,
    },
    closeButton: { color: colors.labelSecondary, fontSize: 30, lineHeight: 30 },
    sheetDivider: {
      height: StyleSheet.hairlineWidth,
      backgroundColor: colors.separator,
    },
    detailsText: { color: colors.labelPrimary, fontSize: 15, lineHeight: 24 },
    exampleText: { color: colors.labelPrimary, fontSize: 15, lineHeight: 23 },
  });
}
