import type {
  CefrLevel,
  LearningGenre,
  SeriesCharacterProfile,
  SeriesParticipationMode,
} from '@domain/index';

// SeriesSetupTextField names a single AI-fillable text field in the setup form.
// Only these fields can be regenerated individually; selected list options are never AI-generated.
export type SeriesSetupTextField =
  | 'title'
  | 'premise'
  | 'mainCharacters'
  | 'userRole';

// GenerateSeriesSetupDraftRequest contains selected setup constraints and optional user text.
export type GenerateSeriesSetupDraftRequest = {
  // regenerateField, when set, asks the AI to replace only this field and keep all others exactly.
  readonly regenerateField?: SeriesSetupTextField;
  // title is preserved when the learner already provided a title.
  readonly title?: string;
  // genre is selected by the learner and must not be generated by AI.
  readonly genre: LearningGenre;
  // cefrLevel is selected by the learner and controls language complexity.
  readonly cefrLevel: CefrLevel;
  // tone is selected by the learner and must shape the generated setup.
  readonly tone: string;
  // participationMode is selected by the learner and must not be generated by AI.
  readonly participationMode: SeriesParticipationMode;
  // premise is preserved when the learner already provided an idea.
  readonly premise?: string;
  // mainCharacters are preserved when the learner already provided characters.
  readonly mainCharacters: readonly string[];
  // characterProfiles preserve pinned dialogue names and descriptions when provided.
  readonly characterProfiles?: readonly SeriesCharacterProfile[];
  // userRole is preserved when character mode already has a learner role.
  readonly userRole?: string;
};

// SeriesSetupDraft is a complete set of text fields ready for local series creation.
export type SeriesSetupDraft = {
  // title is the generated or preserved visible series name.
  readonly title: string;
  // premise is the generated or preserved bounded story setup.
  readonly premise: string;
  // mainCharacters names recurring story characters.
  readonly mainCharacters: readonly string[];
  // characterProfiles pins dialogue names and descriptions for the series.
  readonly characterProfiles: readonly SeriesCharacterProfile[];
  // userRole is returned only for character mode.
  readonly userRole?: string;
};

// SeriesSetupDraftGateway hides the AI setup generator Edge Function transport.
export type SeriesSetupDraftGateway = {
  // generateSeriesSetupDraft returns complete text fields without changing selected options.
  readonly generateSeriesSetupDraft: (
    request: GenerateSeriesSetupDraftRequest,
  ) => Promise<SeriesSetupDraft>;
};
