import type {
  SeriesCharacterProfile,
  SeriesCreativeBrief,
  SeriesParticipationMode,
  SeriesSetupTextField,
} from '@domain/index';

// SeriesSetupGenerationTarget identifies the visible card explicitly requested from AI.
export type SeriesSetupGenerationTarget =
  | 'premise'
  | 'characterProfiles'
  | 'title';

// GenerateSeriesSetupDraftRequest contains selected setup constraints and optional user text.
export type GenerateSeriesSetupDraftRequest = {
  // generationRequestId makes transport retries return one cached AI draft.
  readonly generationRequestId: string;
  // generationTarget prevents a card-local request from expanding unrelated completed fields.
  readonly generationTarget?: SeriesSetupGenerationTarget;
  // title is the current draft value used according to the selected strategy.
  readonly title?: string;
  // participationMode is selected by the learner and must not be generated by AI.
  readonly participationMode: SeriesParticipationMode;
  // premise is the current final draft value, separate from protected creative anchors.
  readonly premise?: string;
  // mainCharacters are the current legacy name list used according to strategy.
  readonly mainCharacters: readonly string[];
  // characterProfiles are the current structured cast used according to strategy.
  readonly characterProfiles?: readonly SeriesCharacterProfile[];
  // emptyCharacterSlotCount preserves visible blank character rows as explicit AI work.
  readonly emptyCharacterSlotCount?: number;
  // userRole is the current character-mode identity used according to strategy.
  readonly userRole?: string;
  // creativeBrief contains exact learner-authored anchors the model must respect.
  readonly creativeBrief: SeriesCreativeBrief;
};

// SeriesSetupDraft is a complete set of text fields ready for local series creation.
export type SeriesSetupDraft = {
  // title is the generated or preserved visible series name.
  readonly title: string;
  // premise is the generated or preserved bounded story setup.
  readonly premise: string;
  // mainCharacters names recurring story characters.
  readonly mainCharacters: readonly string[];
  // characterProfiles pins dialogue names and descriptions for the series.
  readonly characterProfiles: readonly SeriesCharacterProfile[];
  // userRole is returned only for character mode.
  readonly userRole?: string;
  // changedFields identifies values the resolved AI result actually changed.
  readonly changedFields: readonly SeriesSetupTextField[];
};

// SeriesSetupDraftGateway hides the AI setup generator Edge Function transport.
export type SeriesSetupDraftGateway = {
  // generateSeriesSetupDraft returns complete text fields without changing selected options.
  readonly generateSeriesSetupDraft: (
    request: GenerateSeriesSetupDraftRequest,
  ) => Promise<SeriesSetupDraft>;
};
